name = "Bamboo SMP Modpack"
author = "abaan404"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0418c16841450393f0effc3be3cb290982245d0a4d500e6b28c0b2c88876adf0"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
