name = "BambooSMP s4"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5803a446d2aed3df0608781379c6fcde2cdd6d5a1ec1769b768212436cfff230"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
