name = "BambooSMP - WAP s3.5"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b78da9d3804c4139b03072e9a1ce7258dcc80cdee265f58b497996ebd9e9292f"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
