name: upload-server

on:
    workflow_dispatch:
    push:
        branches: [WAP-S3.5]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: Generate server files
              run: |
                  mkdir server/
                  cd server/
                  wget https://github.com/packwiz/packwiz-installer-bootstrap/releases/download/v0.0.3/packwiz-installer-bootstrap.jar
                  java -jar packwiz-installer-bootstrap.jar -g -s server file://$(pwd)/../pack.toml

                  # these mods will crash on a server, remove before uploading
                  rm mods/figura-0.1.5+1.20.1-forge-mc.jar
                  rm mods/oculus-mc1.20.1-1.8.0.jar

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to Server via SFTP
              uses: Dylan700/sftp-upload-action@v1.2.3
              with:
                  server: ${{ secrets.SFTP_HOST }}
                  port: ${{ secrets.SFTP_PORT }}
                  username: ${{ secrets.SFTP_USERNAME }}
                  password: ${{ secrets.SFTP_PASSWORD }}
                  uploads: |
                      server/ => /

    deploy-pages:
      needs: deploy

      permissions:
        pages: write
        id-token: write

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
